field: 77af5a62-d057-494a-91ac-9edf65b6b266 # Content Builder
fieldLayouts:
  7d8c40f9-257c-41b4-8747-551f180cacc5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 127f0d67-cfaf-4e5d-b3f8-111b7fda6f64 # Padding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b392e2e-ab1b-42ce-81a1-01fbd59e5ce6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bed279a-5360-4e96-b92e-3153c98bff40 # Section Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a71662d0-b947-40fe-9aee-693197d4445b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c78e0b43-9945-41ae-bdc4-9e38f07eca01 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdb7e4c4-caa6-40d1-bb93-831a931266f2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cc618569-5c0e-4ff7-9b4a-2fe9ed27af1f # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c36cc61-1f7c-4373-91f1-16aa37ce2c5b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d76b4b4a-101d-4508-8153-84c7205cd9a3
        userCondition: null
fields:
  5bed279a-5360-4e96-b92e-3153c98bff40: # Section Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: sectionTitle
    instructions: null
    name: 'Section Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  127f0d67-cfaf-4e5d-b3f8-111b7fda6f64: # Padding
    columnSuffix: mjnbzisp
    contentColumnType: string
    fieldGroup: null
    handle: padding
    instructions: null
    name: Padding
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Top & bottom'
            -
              - value
              - section-y-padding
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Top Only'
            -
              - value
              - section-t-padding
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Bottom Only'
            -
              - value
              - section-b-padding
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No Padding'
            -
              - value
              - section-no-padding
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c78e0b43-9945-41ae-bdc4-9e38f07eca01: # Button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: null
    name: Button
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: site
    type: lenz\linkfield\fields\LinkField
  cc618569-5c0e-4ff7-9b4a-2fe9ed27af1f: # Background Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: null
    name: 'Background Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: callToAction
name: 'Call To Action'
sortOrder: 2
