field: 77af5a62-d057-494a-91ac-9edf65b6b266 # Content Builder
fieldLayouts:
  5cffcd34-b35a-46b9-afa9-c3f3b295e13d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8a60bb9d-8e34-4487-b809-65134adc6fa1 # Padding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c4076ea-60fd-47cd-8995-455d0b2dbcd1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b9496a7-4539-4c28-91bc-3e51c68f4187 # Embed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e31f9ac5-7f1f-4429-9446-027fbdf0e6f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1107425a-00a9-49dc-81b2-989e058e0fee
        userCondition: null
fields:
  3b9496a7-4539-4c28-91bc-3e51c68f4187: # Embed
    columnSuffix: buzbghct
    contentColumnType: text
    fieldGroup: null
    handle: embed
    instructions: null
    name: Embed
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 3
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  8a60bb9d-8e34-4487-b809-65134adc6fa1: # Padding
    columnSuffix: sxtfpvji
    contentColumnType: string
    fieldGroup: null
    handle: padding
    instructions: null
    name: Padding
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Top & bottom'
            -
              - value
              - section-y-padding
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Top Only'
            -
              - value
              - section-t-padding
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Bottom Only'
            -
              - value
              - section-b-padding
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No Padding'
            -
              - value
              - section-no-padding
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Dropdown
handle: codeEmbed
name: 'Code Embed'
sortOrder: 6
