field: 77af5a62-d057-494a-91ac-9edf65b6b266 # Content Builder
fieldLayouts:
  e426ad6b-03b0-4220-8668-3337284b7c5d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b2007669-385a-48ab-8bb3-88019d7c65de # Padding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac42c12f-111d-4cbb-883c-553898e51e5a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0608b317-3611-4a50-a757-9d0414083f50 # Video Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffe24cd2-8cde-4218-aa2a-15b98218f829
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 78216433-19bd-4871-aee8-1687783498cd
        userCondition: null
fields:
  0608b317-3611-4a50-a757-9d0414083f50: # Video Link
    columnSuffix: ysfzptiq
    contentColumnType: text
    fieldGroup: null
    handle: videoLink
    instructions: 'YouTube or Vimeo'
    name: 'Video Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b2007669-385a-48ab-8bb3-88019d7c65de: # Padding
    columnSuffix: ehibomly
    contentColumnType: string
    fieldGroup: null
    handle: padding
    instructions: null
    name: Padding
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Top & bottom'
            -
              - value
              - section-y-padding
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Top Only'
            -
              - value
              - section-t-padding
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Bottom Only'
            -
              - value
              - section-b-padding
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No Padding'
            -
              - value
              - section-no-padding
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: video
name: Video
sortOrder: 5
