color: null
fieldLayouts:
  5cffcd34-b35a-46b9-afa9-c3f3b295e13d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8a60bb9d-8e34-4487-b809-65134adc6fa1
            handle: padding
            includeInCards: true
            instructions: null
            label: Padding
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c4076ea-60fd-47cd-8995-455d0b2dbcd1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b9496a7-4539-4c28-91bc-3e51c68f4187
            handle: null
            includeInCards: false
            instructions: null
            label: Embed
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e31f9ac5-7f1f-4429-9446-027fbdf0e6f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1107425a-00a9-49dc-81b2-989e058e0fee
        userCondition: null
handle: codeEmbed
hasTitleField: false
icon: null
name: 'Code Embed'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
