color: null
fieldLayouts:
  c626b1d8-1909-423a-a161-eda975647216:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-27T11:58:14-05:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4a9c3468-247d-4f5a-9bb4-cc13ba9aaa61
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T11:58:14-05:00'
            elementCondition: null
            fieldUid: 56f86cc6-5713-447f-8b10-e53f06ef42eb # Hide from Nav
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f733cb5-f471-4dff-b2a3-d81a2354ba71
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T11:58:14-05:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 85a4a23d-3725-49a3-9650-918f3be12037
            userCondition: null
          -
            dateAdded: '2025-01-27T11:58:14-05:00'
            elementCondition: null
            fieldUid: ab8abc7e-2a4d-4858-98ea-9a6954a434da # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43d8cb47-c827-4bf1-9813-485c81b5c326
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T11:58:14-05:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Used when displayed on other pages'
            type: craft\fieldlayoutelements\Tip
            uid: f070e260-a4d3-4c63-b54d-18e032a4f1c6
            userCondition: null
          -
            dateAdded: '2025-01-27T11:58:14-05:00'
            elementCondition: null
            fieldUid: c33fedfd-ec76-45db-93dc-a12697e4a2aa # Listing Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d14775fa-d808-4ae1-803b-8d7ad5dc2ad6
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-01-27T11:58:14-05:00'
            elementCondition: null
            fieldUid: f90a85bd-91b2-462b-acb4-8f265ded647e # Copy
            handle: summary
            includeInCards: false
            instructions: null
            label: Summary
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43ae12e0-d1f6-4042-b214-32aeabadd0de
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-01-27T11:58:14-05:00'
            elementCondition: null
            heading: 'Main Content'
            type: craft\fieldlayoutelements\Heading
            uid: b16c683b-ef39-4e18-86d3-fc3566be5c73
            userCondition: null
          -
            dateAdded: '2025-01-27T11:58:14-05:00'
            elementCondition: null
            fieldUid: f90a85bd-91b2-462b-acb4-8f265ded647e # Copy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7abfbd10-fb81-43de-88fa-fed21b3ec9c7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 02bd7ec5-b7cd-4277-9993-5e39613b939a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-27T11:58:14-05:00'
            elementCondition: null
            fieldUid: 149ec41c-d6de-4ae5-84db-08d285801dd1 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0280f63c-8003-4627-acde-ccde741de390
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 26cb98cc-1949-467c-8b80-02a8b8ef608f
        userCondition: null
handle: contactPage
hasTitleField: true
icon: phone-office
name: 'Contact Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
