color: null
fieldLayouts:
  f3caeaf8-c441-4ad3-a2e8-5ea9abdc3340:
    cardView:
      - 'layoutElement:eab65f53-ddcc-4fe7-86a6-125f0da1b7b0'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-27T16:37:44+00:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: sectionTitle
            includeInCards: false
            instructions: null
            label: 'Section Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bbe1188-9327-49e7-a774-9a8025b4a074
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T16:37:44+00:00'
            elementCondition: null
            fieldUid: f90a85bd-91b2-462b-acb4-8f265ded647e # Copy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f199898-3c5d-4edc-bc9c-8140c1e08e8d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a7f94964-43d2-4526-914c-0aab192f6b93
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-27T16:37:44+00:00'
            elementCondition: null
            fieldUid: 127f0d67-cfaf-4e5d-b3f8-111b7fda6f64 # Padding
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eab65f53-ddcc-4fe7-86a6-125f0da1b7b0
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: a21a221d-a9f7-41b7-aa72-d995d0559cbd
        userCondition: null
handle: copy
hasTitleField: false
icon: font-case
name: Copy
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
