color: null
fieldLayouts:
  623094d9-a7ca-4635-b4df-fb93c89d5b74:
    cardView:
      - 'layoutElement:ba979be8-7b6e-4cd0-a807-5019461b80ee'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-27T16:41:59+00:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: sectionTitle
            includeInCards: true
            instructions: null
            label: 'Section Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba979be8-7b6e-4cd0-a807-5019461b80ee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T16:41:59+00:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: sectionSubtitle
            includeInCards: false
            instructions: null
            label: 'Section Subtitle'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff756a43-1935-4002-8b9e-845dc11eb17f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T16:41:59+00:00'
            elementCondition: null
            fieldUid: f90a85bd-91b2-462b-acb4-8f265ded647e # Copy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2c4d154-8252-461f-bd0a-635b472473d1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e1a117ae-6930-4169-b0c6-525abba96b59
        userCondition: null
handle: copy2
hasTitleField: false
icon: null
name: 'Copy (user guide)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
