color: null
fieldLayouts:
  f3caeaf8-c441-4ad3-a2e8-5ea9abdc3340:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 287bc99a-b762-4452-b6c6-e6084ef63e75
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80c3b02f-d4d4-4fb2-8c5c-1cde8119afad
            handle: sectionTitle
            includeInCards: false
            instructions: null
            label: 'Section Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bbe1188-9327-49e7-a774-9a8025b4a074
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77af2e3b-d586-4daa-b99c-fd4792c204da
            handle: copy
            includeInCards: false
            instructions: null
            label: Copy
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f199898-3c5d-4edc-bc9c-8140c1e08e8d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a7f94964-43d2-4526-914c-0aab192f6b93
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b507c631-830f-46d6-b625-4d4a6df7775c
            handle: padding
            includeInCards: true
            instructions: null
            label: Padding
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eab65f53-ddcc-4fe7-86a6-125f0da1b7b0
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: a21a221d-a9f7-41b7-aa72-d995d0559cbd
        userCondition: null
handle: copy
hasTitleField: false
icon: ''
name: Copy
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
