color: null
fieldLayouts:
  9a7c5f55-c3f5-4e6e-9066-4cae24a1e8fc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d1cb9311-8822-4092-8e29-4605232cc3a5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aac80dd6-df34-4cd2-a92f-14debb37b911
            handle: null
            includeInCards: true
            instructions: null
            label: Fragment
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36176e49-f347-4d1d-9c9f-43876e808579
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ac485a3-5145-4704-b46f-add6c7126e86
        userCondition: null
handle: fragmentBlock
hasTitleField: false
icon: ''
name: 'Fragment Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
