color: emerald
fieldLayouts:
  171a213e-9b33-49e7-bf1d-8056ef4d5c12:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 514527a7-c517-4adb-9d54-efdb1f6be1b0
            userCondition: null
            warning: null
            width: 100
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Summary should only be 2-3 sentences. Image will appear on listing page'
            type: craft\fieldlayoutelements\Tip
            uid: f4aec492-bb0f-40b0-afbf-79a590fca8be
            userCondition: null
          -
            elementCondition: null
            fieldUid: b2f53aa5-81a3-466c-af2d-e30dab4ed3d8 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23da011a-390b-4e37-89a2-4b97651ed706
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 95ce0179-ac46-4ecb-910c-aa91c7a07961 # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ef618f6-08b3-4fcc-a915-60ee481fb8dd
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fbdde691-0df2-4e8e-b1a8-61a1f555fd0e # News Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbaff3bd-2fb9-4f11-a784-51688db844d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Main Content'
            type: craft\fieldlayoutelements\Heading
            uid: d7089c82-6c41-4d83-846b-4bafe2301bac
            userCondition: null
        name: Content
        uid: daf8662e-c051-40ce-9a9f-055743873cb4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 149ec41c-d6de-4ae5-84db-08d285801dd1 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8a6d8cd-2973-4ae5-a913-4014dabf5dab
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: a5bc70bc-debf-4ef0-bf9f-162f96619557
        userCondition: null
handle: news
hasTitleField: true
icon: radio
name: News
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
