color: null
fieldLayouts:
  532fe5e4-df32-4a3a-a746-e5f91f6e168b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-23T17:27:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5e12737a-07df-4361-8f63-0eb9a62a8182
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-23T17:27:03+00:00'
            elementCondition: null
            fieldUid: 8c583e9a-a56d-486d-8550-e7eae61c8088 # Hero - Slider Hero - Slides
            handle: null
            includeInCards: false
            instructions: null
            label: Slides
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61e062bf-9716-4fe4-892c-bc2dadb71721
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e0366ccf-37de-4a01-9c00-95a40acd04f2
        userCondition: null
handle: sliderHero
hasTitleField: false
icon: ''
name: 'Slider Hero'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
