color: null
fieldLayouts:
  cd7a8b0c-f1dc-4657-98cc-8b2e9c46c04f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-23T17:27:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8d8d3cd3-3546-41c5-a3f7-2c9ef34fb971
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-23T17:31:19+00:00'
            elementCondition: null
            fieldUid: b2f53aa5-81a3-466c-af2d-e30dab4ed3d8 # Image
            handle: Image
            includeInCards: false
            instructions: '1900px * 450px'
            label: 'Slide Background Image'
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 089152b0-0d41-4e63-92a8-d83178a4ce67
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-23T17:31:19+00:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: slideTitle
            includeInCards: false
            instructions: null
            label: 'Slide Title'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4a388a4-1eb3-4e3a-8781-e0887b77d13e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-23T17:31:19+00:00'
            elementCondition: null
            fieldUid: f90a85bd-91b2-462b-acb4-8f265ded647e # Copy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9dc85697-b157-4152-bec7-c66e23453a25
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-23T17:31:19+00:00'
            elementCondition: null
            fieldUid: 136d3c61-5e7c-4eb4-afc0-5c78565fbe8b # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0597412a-b607-46e5-a657-aeced9b4a521
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50edff63-4472-47a0-b1de-b7d952adb095
        userCondition: null
handle: slide
hasTitleField: false
icon: gallery-thumbnails
name: Slide
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: '{slideTitle}'
titleTranslationKeyFormat: ''
titleTranslationMethod: site
