headingLevels:
  - 2
  - 3
name: Site
options:
  code:
    indentSequence: '  '
  link:
    addTargetToExternalLinks: false
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
  style:
    definitions:
      -
        classes:
          - mb-20
        element: span
        name: 'Extra Bottom Margin'
      -
        classes:
          - mt-1
          - mb-0
          - leading-tight
        element: p
        name: 'Tight Paragraphs'
toolbar:
  - sourceEditing
  - '|'
  - heading
  - '|'
  - style
  - '|'
  - bold
  - italic
  - bulletedList
  - numberedList
  - outdent
  - indent
  - link
  - alignment
