headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: 'Site Basic'
options:
  code:
    indentSequence: '  '
  link:
    addTargetToExternalLinks: false
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
toolbar:
  - sourceEditing
  - bold
