columnSuffix: null
handle: copyBasic
instructions: null
name: 'Copy Basic'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  css: null
  defaultTransform: null
  fullGraphqlData: false
  headingLevels:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  js: null
  options:
    __assoc__:
      -
        - code
        -
          __assoc__:
            -
              - indentSequence
              - '  '
      -
        - link
        -
          __assoc__:
            -
              - addTargetToExternalLinks
              - false
            -
              - decorators
              -
                __assoc__:
                  -
                    - openInNewTab
                    -
                      __assoc__:
                        -
                          - attributes
                          -
                            __assoc__:
                              -
                                - rel
                                - 'noopener noreferrer'
                              -
                                - target
                                - _blank
                        -
                          - label
                          - 'Open in a new tab'
                        -
                          - mode
                          - manual
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - sourceEditing
    - bold
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
