columnSuffix: vgclrinn
contentColumnType: boolean
handle: enableNoticeBar
instructions: null
name: 'Enable Notice Bar'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Lightswitch
