columnSuffix: null
contentColumnType: boolean
handle: hideFromNav
instructions: null
name: 'Hide from Nav'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
