columnSuffix: null
handle: lightSwitch
instructions: null
name: 'Light Switch'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Lightswitch
