columnSuffix: sxtfpvji
handle: padding4
instructions: null
name: 'Content Builder - Code Embed - Padding'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Top & bottom'
        -
          - value
          - section-y-padding
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Top Only'
        -
          - value
          - section-t-padding
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Bottom Only'
        -
          - value
          - section-b-padding
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'No Padding'
        -
          - value
          - section-no-padding
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Dropdown
