columnSuffix: mjnbzisp
handle: padding
instructions: null
name: Padding
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Top & bottom'
        -
          - value
          - section-y-padding
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Top Only'
        -
          - value
          - section-t-padding
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Bottom Only'
        -
          - value
          - section-b-padding
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'No Padding'
        -
          - value
          - section-no-padding
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Dropdown
