columnSuffix: null
handle: sectionTitle
instructions: null
name: 'Content Builder - Call To Action - Section Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
