columnSuffix: null
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields:
    - seoPreview
    - ogTitle
    - ogDescription
    - ogImage
  facebookTabEnabled: '1'
  generalEnabledFields:
    - seoPreview
    - seoTitle
    - seoDescription
    - seoImage
  generalTabEnabled: '1'
  sitemapEnabledFields:
    - sitemapUrls
    - sitemapChangeFreq
    - sitemapPriority
  sitemapTabEnabled: '1'
  twitterEnabledFields:
    - seoPreview
    - twitterTitle
    - twitterDescription
    - twitterImage
  twitterTabEnabled: '1'
translationKeyFormat: null
translationMethod: site
type: nystudio107\seomatic\fields\SeoSettings
