columnSuffix: null
handle: slides
instructions: null
name: 'Hero - Slider Hero - Slides'
searchable: false
settings:
  errorMessage: 'Unable to find component class ''verbb\supertable\fields\SuperTableField''.'
  expectedType: verbb\supertable\fields\SuperTableField
  settings:
    __assoc__:
      0:
        - minRows
        - 1
      1:
        - maxRows
        - 5
      2:
        - contentTable
        - '{{%stc_8_slides}}'
      3:
        - propagationMethod
        - none
      6:
        - fieldLayout
        - row
      8:
        - columns
        -
          __assoc__:
            -
              - d5f8da04-ca55-4c9f-8605-e7f8779e82b8 # Image
              -
                __assoc__:
                  -
                    - width
                    - ''
            -
              - 01313804-5d1a-410f-9da8-42ea30ae231d # Slide Title
              -
                __assoc__:
                  -
                    - width
                    - ''
            -
              - 8491df26-ac74-440e-8ce9-403654b8ce98 # Copy
              -
                __assoc__:
                  -
                    - width
                    - ''
            -
              - 59621bb5-03e8-481a-b377-5e08b5a79c12 # Button
              -
                __assoc__:
                  -
                    - width
                    - ''
      9:
        - changedFieldIndicator
        - 1852189373
      10:
        - blockTypeFields
        - 0
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
