columnSuffix: null
handle: slides
instructions: null
name: 'Hero - Slider Hero - Slides'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - d399ecfb-7ec8-47d8-84ed-b8447e779a67 # Slide
  includeTableView: false
  maxEntries: 5
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
