dateModified: 1723300584
elementSources:
  craft\elements\Entry:
    -
      heading: Structures
      type: heading
    -
      disabled: false
      key: 'section:666b31c2-d6d5-4e80-b9aa-f57b66d5b54a' # Pages
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      heading: Channels
      type: heading
    -
      key: 'section:9c12e5ad-18e9-498f-bf50-489513409007' # News
      type: native
    -
      heading: 'Supporting Content'
      type: heading
    -
      key: singles
      tableAttributes:
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:ce27286a-7635-4494-9c9c-77f2d73352f4' # Fragments
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      heading: ''
      type: heading
    -
      key: '*'
      type: native
    -
      heading: 'User Guide'
      type: heading
    -
      key: 'section:0784ad32-f952-40b1-9f6c-d0e67d502551' # User Guide
      type: native
    -
      heading: Categories
      type: heading
    -
      key: 'section:4b342e70-0223-4c29-9237-86a023f74f1b' # News Categories
      type: native
email:
  fromEmail: $SYSTEM_EMAIL
  fromName: $SENDER_NAME
  replyToEmail: $FROM_EMAIL
  template: null
  transportSettings:
    encryptionMethod: ''
    host: $EMAIL_HOSTNAME
    password: $EMAIL_PASSWORD
    port: $EMAIL_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $EMAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: $ASSET_BASE_PATH
    type: craft\fs\Local
    url: $ASSET_BASE_URL
  userGuide:
    hasUrls: true
    name: 'User Guide'
    settings:
      path: $GUIDE_BASE_PATH
    type: craft\fs\Local
    url: $GUIDE_BASE_URL
meta:
  __names__:
    1a78d395-d81a-4b77-8da7-30a49123bbee: English # English
    2b01b0d7-0c08-4e47-8041-e2b6a7fc855b: Caption # Caption
    2fcd48d2-b2b1-479f-9015-016904e4eab4: 'Craft Starter' # Craft Starter
    3e09420e-30db-49dd-9520-4775f6667303: 'Site Basic' # Site Basic
    4b342e70-0223-4c29-9237-86a023f74f1b: 'News Categories' # News Categories
    5bca37e0-a30f-48fd-9fde-3105fb9d9738: 'Notice Bar' # Notice Bar
    9c12e5ad-18e9-498f-bf50-489513409007: News # News
    12c7de12-987a-4aa4-890f-ec5cde880851: 'Fallback Image' # Fallback Image
    12f17257-6f1c-4e4c-837e-17ad76241a60: Site # Site
    29d88d99-dd38-43f6-9ac5-3438833c75ba: 'Error 404' # Error 404
    43dded62-bf6e-4b04-9dd3-a527a9044c86: hyper # hyper
    48d0d0b8-2e48-4232-8b09-a401c6493902: 'Fragment Block' # Fragment Block
    51b9c3fc-be2a-4ef3-9f2c-66372327c604: News # News
    52f12f1b-ba11-48f3-985d-0ee6e2a6dc4e: 'Notice Bar Location' # Notice Bar Location
    56f86cc6-5713-447f-8b10-e53f06ef42eb: 'Hide from Nav' # Hide from Nav
    57a74cde-de83-4b69-88ff-a4472daac7f7: 'Call To Action' # Call To Action
    70f5d47b-4830-4d51-95fe-bc0f7ccc0670: Uploads # Uploads
    77af5a62-d057-494a-91ac-9edf65b6b266: 'Content Builder' # Content Builder
    95ce0179-ac46-4ecb-910c-aa91c7a07961: Summary # Summary
    127f0d67-cfaf-4e5d-b3f8-111b7fda6f64: 'Content Builder - Call To Action - Padding' # Content Builder - Call To Action - Padding
    136d3c61-5e7c-4eb4-afc0-5c78565fbe8b: Button # Button
    149ec41c-d6de-4ae5-84db-08d285801dd1: SEO # SEO
    170a124d-5ba5-43f5-a663-8f85be97b38b: Default # Default
    415a954c-eb55-4533-9ffd-64b3eade9469: Fallback # Fallback
    475a351b-2442-4767-8ab6-1b39216d0c61: 'User Guide' # User Guide
    666b31c2-d6d5-4e80-b9aa-f57b66d5b54a: Pages # Pages
    0784ad32-f952-40b1-9f6c-d0e67d502551: 'User Guide' # User Guide
    0878c4de-b946-4c8e-bcce-fe18cd77a73e: 'Site Admin' # Site Admin
    4116f227-348c-4509-bc7a-6767a28fd40c: 'Contact Page' # Contact Page
    5489ed3b-28c1-4a26-ac7e-97b0182e6652: 'Enable Notice Bar' # Enable Notice Bar
    8084d027-d1a0-424e-930b-a4217b9862f2: 'Public Schema' # Public Schema
    8491df26-ac74-440e-8ce9-403654b8ce98: Copy # Copy
    59621bb5-03e8-481a-b377-5e08b5a79c12: Button # Button
    70339fac-606b-4827-9a19-c97a3f0bd59c: Copy # Copy
    408314ae-e32d-471b-a729-25f4ce759ac4: 'Notice Bar' # Notice Bar
    01313804-5d1a-410f-9da8-42ea30ae231d: 'Slide Title' # Slide Title
    ab8abc7e-2a4d-4858-98ea-9a6954a434da: Hero # Hero
    b2f53aa5-81a3-466c-af2d-e30dab4ed3d8: Image # Image
    b9d8d694-0313-4709-a12e-06b36b2333c7: Simple # Simple
    b9fdef79-5b63-4932-a9aa-8d18f937e6d9: Français # Français
    b312d78c-b490-46da-aeff-70a1be5a5505: 'Error 404' # Error 404
    bb838d9b-476f-487c-8cc2-8e01b9423d92: Pages # Pages
    c33fedfd-ec76-45db-93dc-a12697e4a2aa: 'Listing Image' # Listing Image
    c78e0b43-9945-41ae-bdc4-9e38f07eca01: Button # Button
    c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde: Input # Input
    c166cd47-6f64-49e0-b33d-6aceadb3fcc3: Fragments # Fragments
    c951c9a0-1cca-4210-bef8-2d3d0446e841: 'Related Entries' # Related Entries
    ce14c790-b25f-464b-8ce8-0e949adc707b: 'Light Switchh' # Light Switchh
    ce27286a-7635-4494-9c9c-77f2d73352f4: Fragments # Fragments
    d5f8da04-ca55-4c9f-8605-e7f8779e82b8: Image # Image
    d19b4314-0267-4e95-9e63-2462a334eea1: 'User Guide' # User Guide
    d974bf8d-647d-45f3-98be-0733d5e3e1ba: 'User Guide' # User Guide
    dbff8535-c8bd-4629-bc58-732972504e1b: 'Alt Text' # Alt Text
    e3dea9df-426f-43a5-96fd-927882533aa9: 'News Listing' # News Listing
    ea7fe716-adee-4200-a8ca-15362418cd97: Home # Home
    ef488e30-b35e-4bf8-87a3-34f0f76b622f: 'News Categories' # News Categories
    f4da8483-be1a-439d-8918-afde0ea14454: Text # Text
    f90a85bd-91b2-462b-acb4-8f265ded647e: Copy # Copy
    fbdde691-0df2-4e8e-b1a8-61a1f555fd0e: 'News Categories' # News Categories
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'On behalf of'
      prependSubject: 'New message from Your Website'
      successFlashMessage: 'Your message has been sent.'
      toEmail: $TO_EMAIL
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: ''
      cacheBusting: true
      cssFile: /assets/css/cp-css.css
  hyper:
    edition: standard
    enabled: true
    licenseKey: KJD0ZOPA01HM1YYCNCJ3ZA2Z
    schemaVersion: 1.0.0
  knock-knock:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 0F9VOPZ558WMQISLHBLYMB51
    schemaVersion: 3.0.12
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 0
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: '1'
      truncateTitleTags: '1'
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $SITE_NAME
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: America/Toronto
