defaultPlacement: end
enableVersioning: true
entryTypes:
  - 51b9c3fc-be2a-4ef3-9f2c-66372327c604 # News
handle: news
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1a78d395-d81a-4b77-8da7-30a49123bbee: # English
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: 'news/{slug}'
  b9fdef79-5b63-4932-a9aa-8d18f937e6d9: # Français
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: 'news/{slug}'
type: channel
