defaultPlacement: end
enableVersioning: true
entryTypes:
  - 4116f227-348c-4509-bc7a-6767a28fd40c # Contact Page
  - bb838d9b-476f-487c-8cc2-8e01b9423d92 # Pages
  - e3dea9df-426f-43a5-96fd-927882533aa9 # News Listing
  - ea7fe716-adee-4200-a8ca-15362418cd97 # Home
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1a78d395-d81a-4b77-8da7-30a49123bbee: # English
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 536c7846-2d54-4625-a65d-1a546df44223
type: structure
